/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author Carlos
 */
public class detalleControl extends javax.swing.JFrame {
    
    int xMouse, yMouse;
    public detalleControl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        empresa = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        bg_lateral = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        cantidadLbl = new javax.swing.JLabel();
        cantidadTxt = new javax.swing.JTextField();
        cantidadSeparator = new javax.swing.JSeparator();
        punitLbl = new javax.swing.JLabel();
        punitTxt = new javax.swing.JTextField();
        punitSeparator = new javax.swing.JSeparator();
        importeLbl = new javax.swing.JLabel();
        importeTxt = new javax.swing.JTextField();
        importeSeparator = new javax.swing.JSeparator();
        adelantoLbl = new javax.swing.JLabel();
        adelantoTxt = new javax.swing.JTextField();
        adelantoSeparator = new javax.swing.JSeparator();
        fechaLbl = new javax.swing.JLabel();
        fechaTxt = new javax.swing.JTextField();
        fechaSeparator = new javax.swing.JSeparator();
        cobraLbl = new javax.swing.JLabel();
        cobrarTxt = new javax.swing.JTextField();
        cobrarSeparator = new javax.swing.JSeparator();
        generarBtn = new javax.swing.JPanel();
        generarTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(244, 247, 254));
        bg.setForeground(new java.awt.Color(244, 247, 254));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        empresa.setBackground(new java.awt.Color(244, 247, 254));
        empresa.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        empresa.setForeground(new java.awt.Color(244, 247, 254));
        empresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empresa.setText("MADERERA");
        bg.add(empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 300, -1));

        titulo.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("DETALLE DE CONTROL DE MADERA");
        bg.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 500, 30));

        bg_lateral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N
        bg.add(bg_lateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 300, 500));

        header.setBackground(new java.awt.Color(244, 247, 254));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(244, 247, 254));
        exitBtn.setForeground(new java.awt.Color(244, 247, 254));

        exitTxt.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(760, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        cantidadLbl.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        cantidadLbl.setForeground(new java.awt.Color(0, 0, 0));
        cantidadLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantidadLbl.setText("CANTIDAD");
        bg.add(cantidadLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 80, 30));

        cantidadTxt.setBackground(new java.awt.Color(244, 247, 254));
        cantidadTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cantidadTxt.setForeground(new java.awt.Color(204, 204, 204));
        cantidadTxt.setBorder(null);
        cantidadTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cantidadTxtMousePressed(evt);
            }
        });
        cantidadTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadTxtActionPerformed(evt);
            }
        });
        cantidadTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cantidadTxtKeyPressed(evt);
            }
        });
        bg.add(cantidadTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 80, 30));
        bg.add(cantidadSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 80, 10));

        punitLbl.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        punitLbl.setForeground(new java.awt.Color(0, 0, 0));
        punitLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        punitLbl.setText("P. UNITARIO");
        bg.add(punitLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 80, 30));

        punitTxt.setBackground(new java.awt.Color(244, 247, 254));
        punitTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        punitTxt.setForeground(new java.awt.Color(204, 204, 204));
        punitTxt.setBorder(null);
        punitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                punitTxtMousePressed(evt);
            }
        });
        punitTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                punitTxtActionPerformed(evt);
            }
        });
        punitTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                punitTxtKeyPressed(evt);
            }
        });
        bg.add(punitTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 80, 30));
        bg.add(punitSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 80, 10));

        importeLbl.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        importeLbl.setForeground(new java.awt.Color(0, 0, 0));
        importeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        importeLbl.setText("IMPORTE");
        bg.add(importeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 80, 30));

        importeTxt.setBackground(new java.awt.Color(244, 247, 254));
        importeTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        importeTxt.setForeground(new java.awt.Color(204, 204, 204));
        importeTxt.setBorder(null);
        importeTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                importeTxtMousePressed(evt);
            }
        });
        importeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importeTxtActionPerformed(evt);
            }
        });
        importeTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                importeTxtKeyPressed(evt);
            }
        });
        bg.add(importeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 80, 30));
        bg.add(importeSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 80, 10));

        adelantoLbl.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        adelantoLbl.setForeground(new java.awt.Color(0, 0, 0));
        adelantoLbl.setText("ADELANTO");
        bg.add(adelantoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 90, 30));

        adelantoTxt.setBackground(new java.awt.Color(244, 247, 254));
        adelantoTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        adelantoTxt.setForeground(new java.awt.Color(204, 204, 204));
        adelantoTxt.setBorder(null);
        adelantoTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                adelantoTxtMousePressed(evt);
            }
        });
        adelantoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adelantoTxtActionPerformed(evt);
            }
        });
        adelantoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adelantoTxtKeyPressed(evt);
            }
        });
        bg.add(adelantoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 110, 30));
        bg.add(adelantoSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 110, 10));

        fechaLbl.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        fechaLbl.setForeground(new java.awt.Color(0, 0, 0));
        fechaLbl.setText("FECHA");
        bg.add(fechaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 60, 30));

        fechaTxt.setBackground(new java.awt.Color(244, 247, 254));
        fechaTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        fechaTxt.setForeground(new java.awt.Color(204, 204, 204));
        fechaTxt.setBorder(null);
        fechaTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fechaTxtMousePressed(evt);
            }
        });
        fechaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaTxtActionPerformed(evt);
            }
        });
        fechaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fechaTxtKeyPressed(evt);
            }
        });
        bg.add(fechaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 110, 30));
        bg.add(fechaSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 110, 10));

        cobraLbl.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        cobraLbl.setForeground(new java.awt.Color(0, 0, 0));
        cobraLbl.setText("POR COBRAR");
        bg.add(cobraLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 90, 30));

        cobrarTxt.setBackground(new java.awt.Color(244, 247, 254));
        cobrarTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cobrarTxt.setForeground(new java.awt.Color(204, 204, 204));
        cobrarTxt.setBorder(null);
        cobrarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cobrarTxtMousePressed(evt);
            }
        });
        cobrarTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobrarTxtActionPerformed(evt);
            }
        });
        cobrarTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cobrarTxtKeyPressed(evt);
            }
        });
        bg.add(cobrarTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 110, 30));
        bg.add(cobrarSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 110, 10));

        generarBtn.setBackground(new java.awt.Color(0, 96, 170));
        generarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        generarTxt.setBackground(new java.awt.Color(0, 96, 170));
        generarTxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        generarTxt.setForeground(new java.awt.Color(244, 247, 254));
        generarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        generarTxt.setText("GENERAR");
        generarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        generarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generarTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                generarTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                generarTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout generarBtnLayout = new javax.swing.GroupLayout(generarBtn);
        generarBtn.setLayout(generarBtnLayout);
        generarBtnLayout.setHorizontalGroup(
            generarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(generarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        generarBtnLayout.setVerticalGroup(
            generarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(generarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(generarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adelantoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adelantoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adelantoTxtActionPerformed

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        dispose();
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(new Color(244,247,254));
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitBtn.setBackground(new Color(244,247,254));
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

    private void generarTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generarTxtMouseEntered
        generarBtn.setBackground(new Color(0, 156, 223));
    }//GEN-LAST:event_generarTxtMouseEntered

    private void generarTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generarTxtMouseExited
        generarBtn.setBackground(new Color(0,96,170));
    }//GEN-LAST:event_generarTxtMouseExited

    private void adelantoTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adelantoTxtMousePressed

    }//GEN-LAST:event_adelantoTxtMousePressed

    private void generarTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generarTxtMouseClicked

    }//GEN-LAST:event_generarTxtMouseClicked

    private void adelantoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adelantoTxtKeyPressed

    }//GEN-LAST:event_adelantoTxtKeyPressed

    private void cantidadTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cantidadTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadTxtMousePressed

    private void cantidadTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadTxtActionPerformed

    private void cantidadTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadTxtKeyPressed

    private void punitTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_punitTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_punitTxtMousePressed

    private void punitTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_punitTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_punitTxtActionPerformed

    private void punitTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_punitTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_punitTxtKeyPressed

    private void importeTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importeTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_importeTxtMousePressed

    private void importeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_importeTxtActionPerformed

    private void importeTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_importeTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_importeTxtKeyPressed

    private void fechaTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaTxtMousePressed

    private void fechaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaTxtActionPerformed

    private void fechaTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechaTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaTxtKeyPressed

    private void cobrarTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cobrarTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cobrarTxtMousePressed

    private void cobrarTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobrarTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cobrarTxtActionPerformed

    private void cobrarTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cobrarTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cobrarTxtKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(detalleControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(detalleControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(detalleControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(detalleControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new detalleControl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adelantoLbl;
    private javax.swing.JSeparator adelantoSeparator;
    private javax.swing.JTextField adelantoTxt;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel bg_lateral;
    private javax.swing.JLabel cantidadLbl;
    private javax.swing.JSeparator cantidadSeparator;
    private javax.swing.JTextField cantidadTxt;
    private javax.swing.JLabel cobraLbl;
    private javax.swing.JSeparator cobrarSeparator;
    private javax.swing.JTextField cobrarTxt;
    private javax.swing.JLabel empresa;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JLabel fechaLbl;
    private javax.swing.JSeparator fechaSeparator;
    private javax.swing.JTextField fechaTxt;
    private javax.swing.JPanel generarBtn;
    private javax.swing.JLabel generarTxt;
    private javax.swing.JPanel header;
    private javax.swing.JLabel importeLbl;
    private javax.swing.JSeparator importeSeparator;
    private javax.swing.JTextField importeTxt;
    private javax.swing.JLabel punitLbl;
    private javax.swing.JSeparator punitSeparator;
    private javax.swing.JTextField punitTxt;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
