/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author Carlos
 */
public class frmRegCtrlMad extends javax.swing.JFrame {
    
    int xMouse, yMouse;
    public frmRegCtrlMad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        fotoMadera = new javax.swing.JLabel();
        largoLbl = new javax.swing.JLabel();
        largoCmb = new javax.swing.JComboBox<>();
        largoLbl1 = new javax.swing.JLabel();
        largoCmb1 = new javax.swing.JComboBox<>();
        cantidadLbl = new javax.swing.JLabel();
        cantidadTxt = new javax.swing.JTextField();
        cantidadSeparator = new javax.swing.JSeparator();
        piesLbl = new javax.swing.JLabel();
        piesTxt = new javax.swing.JTextField();
        piesSeparator = new javax.swing.JSeparator();
        grabarBtn = new javax.swing.JPanel();
        grabarTxt = new javax.swing.JLabel();
        editarBtn = new javax.swing.JPanel();
        editarTxt = new javax.swing.JLabel();
        borrarBtn = new javax.swing.JPanel();
        borrarTxt = new javax.swing.JLabel();
        salirBtn = new javax.swing.JPanel();
        salirTxt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bg_img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(244, 247, 254));
        bg.setForeground(new java.awt.Color(244, 247, 254));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(244, 247, 254));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(244, 247, 254));
        exitBtn.setForeground(new java.awt.Color(244, 247, 254));

        exitTxt.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 40));

        titulo.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("REGISTRO DE CONTROL DE MADERA");
        bg.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1020, 30));

        fotoMadera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/madera.png"))); // NOI18N
        fotoMadera.setText("jLabel1");
        fotoMadera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 96, 170)));
        bg.add(fotoMadera, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 320, 260));

        largoLbl.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        largoLbl.setForeground(new java.awt.Color(0, 0, 0));
        largoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        largoLbl.setText("LARGO");
        bg.add(largoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 80, 30));

        largoCmb.setBackground(new java.awt.Color(242, 242, 242));
        largoCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Largo", "2 mts", "2.5 mts", "3 mts" }));
        largoCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largoCmbActionPerformed(evt);
            }
        });
        bg.add(largoCmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 80, 30));

        largoLbl1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        largoLbl1.setForeground(new java.awt.Color(0, 0, 0));
        largoLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        largoLbl1.setText("NUMERO DE MEDIDAS");
        bg.add(largoLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 130, 30));

        largoCmb1.setBackground(new java.awt.Color(242, 242, 242));
        largoCmb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medidas", "4 x 1", "3 x 2", "2 x 2" }));
        largoCmb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largoCmb1ActionPerformed(evt);
            }
        });
        bg.add(largoCmb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 130, 30));

        cantidadLbl.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        cantidadLbl.setForeground(new java.awt.Color(0, 0, 0));
        cantidadLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantidadLbl.setText("CANTIDAD");
        bg.add(cantidadLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 80, 30));

        cantidadTxt.setBackground(new java.awt.Color(244, 247, 254));
        cantidadTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cantidadTxt.setForeground(new java.awt.Color(204, 204, 204));
        cantidadTxt.setBorder(null);
        cantidadTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cantidadTxtMousePressed(evt);
            }
        });
        cantidadTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadTxtActionPerformed(evt);
            }
        });
        cantidadTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cantidadTxtKeyPressed(evt);
            }
        });
        bg.add(cantidadTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 80, 30));
        bg.add(cantidadSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 80, 10));

        piesLbl.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        piesLbl.setForeground(new java.awt.Color(0, 0, 0));
        piesLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        piesLbl.setText("PIES");
        bg.add(piesLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 80, 30));

        piesTxt.setEditable(false);
        piesTxt.setBackground(new java.awt.Color(242, 242, 242));
        piesTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        piesTxt.setForeground(new java.awt.Color(204, 204, 204));
        piesTxt.setBorder(null);
        piesTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                piesTxtMousePressed(evt);
            }
        });
        piesTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piesTxtActionPerformed(evt);
            }
        });
        piesTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                piesTxtKeyPressed(evt);
            }
        });
        bg.add(piesTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 80, 30));
        bg.add(piesSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 80, 10));

        grabarBtn.setBackground(new java.awt.Color(0, 96, 170));
        grabarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        grabarTxt.setBackground(new java.awt.Color(0, 96, 170));
        grabarTxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        grabarTxt.setForeground(new java.awt.Color(244, 247, 254));
        grabarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grabarTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        grabarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        grabarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grabarTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                grabarTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                grabarTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout grabarBtnLayout = new javax.swing.GroupLayout(grabarBtn);
        grabarBtn.setLayout(grabarBtnLayout);
        grabarBtnLayout.setHorizontalGroup(
            grabarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grabarBtnLayout.createSequentialGroup()
                .addComponent(grabarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        grabarBtnLayout.setVerticalGroup(
            grabarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(grabarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg.add(grabarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 60, 40));

        editarBtn.setBackground(new java.awt.Color(0, 96, 170));
        editarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        editarTxt.setBackground(new java.awt.Color(0, 96, 170));
        editarTxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        editarTxt.setForeground(new java.awt.Color(244, 247, 254));
        editarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editarTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        editarTxt.setText("EDITAR");
        editarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editarTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editarTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout editarBtnLayout = new javax.swing.GroupLayout(editarBtn);
        editarBtn.setLayout(editarBtnLayout);
        editarBtnLayout.setHorizontalGroup(
            editarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, Short.MAX_VALUE)
        );
        editarBtnLayout.setVerticalGroup(
            editarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 17, Short.MAX_VALUE)
        );

        bg.add(editarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 110, 40));

        borrarBtn.setBackground(new java.awt.Color(0, 96, 170));
        borrarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        borrarTxt.setBackground(new java.awt.Color(0, 96, 170));
        borrarTxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        borrarTxt.setForeground(new java.awt.Color(244, 247, 254));
        borrarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        borrarTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/borrar.png"))); // NOI18N
        borrarTxt.setText("BORRAR");
        borrarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        borrarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrarTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                borrarTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                borrarTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout borrarBtnLayout = new javax.swing.GroupLayout(borrarBtn);
        borrarBtn.setLayout(borrarBtnLayout);
        borrarBtnLayout.setHorizontalGroup(
            borrarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(borrarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, Short.MAX_VALUE)
        );
        borrarBtnLayout.setVerticalGroup(
            borrarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(borrarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 17, Short.MAX_VALUE)
        );

        bg.add(borrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 110, 40));

        salirBtn.setBackground(new java.awt.Color(0, 96, 170));
        salirBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        salirTxt.setBackground(new java.awt.Color(0, 96, 170));
        salirTxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        salirTxt.setForeground(new java.awt.Color(244, 247, 254));
        salirTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salirTxt.setText("SALIR");
        salirTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salirTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout salirBtnLayout = new javax.swing.GroupLayout(salirBtn);
        salirBtn.setLayout(salirBtnLayout);
        salirBtnLayout.setHorizontalGroup(
            salirBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salirTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        salirBtnLayout.setVerticalGroup(
            salirBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salirTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg.add(salirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 100, 110, 40));

        jScrollPane1.setBackground(new java.awt.Color(242, 242, 242));

        jTable1.setBackground(new java.awt.Color(242, 242, 242));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Espesor", "Ancho", "Largo", "Cantidad", "Pies"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 580, 520));

        bg_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo bl.jpg"))); // NOI18N
        bg.add(bg_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1020, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        dispose();
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(new Color(244,247,254));
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitBtn.setBackground(new Color(244,247,254));
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

    private void cantidadTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cantidadTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadTxtMousePressed

    private void cantidadTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadTxtActionPerformed

    private void cantidadTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadTxtKeyPressed

    private void salirTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirTxtMouseClicked
        dispose();
    }//GEN-LAST:event_salirTxtMouseClicked

    private void salirTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirTxtMouseEntered
        salirBtn.setBackground(new Color(0, 156, 223));
    }//GEN-LAST:event_salirTxtMouseEntered

    private void salirTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirTxtMouseExited
        salirBtn.setBackground(new Color(0,96,170));
    }//GEN-LAST:event_salirTxtMouseExited

    private void borrarTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarTxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_borrarTxtMouseClicked

    private void borrarTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarTxtMouseEntered
        borrarBtn.setBackground(new Color(0, 156, 223));
    }//GEN-LAST:event_borrarTxtMouseEntered

    private void borrarTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarTxtMouseExited
        borrarBtn.setBackground(new Color(0,96,170));
    }//GEN-LAST:event_borrarTxtMouseExited

    private void grabarTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grabarTxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_grabarTxtMouseClicked

    private void grabarTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grabarTxtMouseEntered
        grabarBtn.setBackground(new Color(0, 156, 223));
    }//GEN-LAST:event_grabarTxtMouseEntered

    private void grabarTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grabarTxtMouseExited
        grabarBtn.setBackground(new Color(0,96,170));
    }//GEN-LAST:event_grabarTxtMouseExited

    private void editarTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarTxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_editarTxtMouseClicked

    private void editarTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarTxtMouseEntered
        editarBtn.setBackground(new Color(0, 156, 223));
    }//GEN-LAST:event_editarTxtMouseEntered

    private void editarTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarTxtMouseExited
        editarBtn.setBackground(new Color(0,96,170));
    }//GEN-LAST:event_editarTxtMouseExited

    private void largoCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largoCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_largoCmbActionPerformed

    private void largoCmb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largoCmb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_largoCmb1ActionPerformed

    private void piesTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piesTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_piesTxtMousePressed

    private void piesTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piesTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_piesTxtActionPerformed

    private void piesTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_piesTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_piesTxtKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegCtrlMad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegCtrlMad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegCtrlMad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegCtrlMad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegCtrlMad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel bg_img;
    private javax.swing.JPanel borrarBtn;
    private javax.swing.JLabel borrarTxt;
    private javax.swing.JLabel cantidadLbl;
    private javax.swing.JSeparator cantidadSeparator;
    private javax.swing.JTextField cantidadTxt;
    private javax.swing.JPanel editarBtn;
    private javax.swing.JLabel editarTxt;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JLabel fotoMadera;
    private javax.swing.JPanel grabarBtn;
    private javax.swing.JLabel grabarTxt;
    private javax.swing.JPanel header;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> largoCmb;
    private javax.swing.JComboBox<String> largoCmb1;
    private javax.swing.JLabel largoLbl;
    private javax.swing.JLabel largoLbl1;
    private javax.swing.JLabel piesLbl;
    private javax.swing.JSeparator piesSeparator;
    private javax.swing.JTextField piesTxt;
    private javax.swing.JPanel salirBtn;
    private javax.swing.JLabel salirTxt;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
