/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;
import modelo.DAOTipoMadera;
import modelo.DTOTipoMadera;

/**
 *
 * @author Carlos
 */
public class frmTpMadera extends javax.swing.JFrame {

    int xMouse, yMouse;

    public frmTpMadera() {
        initComponents();
        verProducto();
        habilitarBotones(false, false, false, false, true, false, false, false, true);
    }

    void limpiar() {
        codTxt.setText("");
        largoTxt.setText("");
        anchoTxt.setText("");
        espesorTxt.setText("");
        codTxt.requestFocus();
    }

    void verProducto() {
        DefaultTableModel modeloproducto;
        DAOTipoMadera oDProd = new DAOTipoMadera();
        modeloproducto = oDProd.verProducto();
        tblTipoMadera.setModel(modeloproducto);

    }

    void habilitarBotones(boolean c, boolean l, boolean an, boolean es, boolean n, boolean g, boolean e, boolean b, boolean s) {
        codTxt.setEnabled(c);
        largoTxt.setEnabled(l);
        anchoTxt.setEnabled(an);
        espesorTxt.setEnabled(es);
        nuevoTxt.setEnabled(n);
        grabarTxt.setEnabled(g);
        editarTxt.setEnabled(e);
        borrarTxt.setEnabled(b);
        salirTxt.setEnabled(s);

        // Define color para los botones habilitados y deshabilitados
        Color enabledColor = (new Color(0, 96, 170));
        Color disabledColor = Color.DARK_GRAY;

        nuevoBtn.setBackground(n ? enabledColor : disabledColor);
        grabarBtn.setBackground(g ? enabledColor : disabledColor);
        editarBtn.setBackground(e ? enabledColor : disabledColor);
        borrarBtn.setBackground(b ? enabledColor : disabledColor);
        salirBtn.setBackground(s ? enabledColor : disabledColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        fotoMadera = new javax.swing.JLabel();
        codLbl = new javax.swing.JLabel();
        codTxt = new javax.swing.JTextField();
        codSeparator = new javax.swing.JSeparator();
        largoLbl = new javax.swing.JLabel();
        largoTxt = new javax.swing.JTextField();
        largoSeparator = new javax.swing.JSeparator();
        anchoLbl = new javax.swing.JLabel();
        anchoTxt = new javax.swing.JTextField();
        anchoSeparator = new javax.swing.JSeparator();
        espesorLbl = new javax.swing.JLabel();
        espesorTxt = new javax.swing.JTextField();
        espesorSeparator = new javax.swing.JSeparator();
        nuevoBtn = new javax.swing.JPanel();
        nuevoTxt = new javax.swing.JLabel();
        grabarBtn = new javax.swing.JPanel();
        grabarTxt = new javax.swing.JLabel();
        editarBtn = new javax.swing.JPanel();
        editarTxt = new javax.swing.JLabel();
        borrarBtn = new javax.swing.JPanel();
        borrarTxt = new javax.swing.JLabel();
        salirBtn = new javax.swing.JPanel();
        salirTxt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTipoMadera = new javax.swing.JTable();
        bg_img = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(244, 247, 254));
        bg.setForeground(new java.awt.Color(244, 247, 254));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(244, 247, 254));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(244, 247, 254));
        exitBtn.setForeground(new java.awt.Color(244, 247, 254));

        exitTxt.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 40));

        titulo.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("REGISTRO DE TIPOS DE MADERAS");
        bg.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1020, 30));

        fotoMadera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/madera.png"))); // NOI18N
        fotoMadera.setText("jLabel1");
        fotoMadera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 96, 170)));
        bg.add(fotoMadera, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 320, 260));

        codLbl.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        codLbl.setForeground(new java.awt.Color(0, 0, 0));
        codLbl.setText("CODIGO");
        bg.add(codLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 60, 30));

        codTxt.setBackground(new java.awt.Color(242, 242, 242));
        codTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        codTxt.setForeground(new java.awt.Color(0, 0, 0));
        codTxt.setBorder(null);
        codTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                codTxtMousePressed(evt);
            }
        });
        codTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codTxtActionPerformed(evt);
            }
        });
        codTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codTxtKeyPressed(evt);
            }
        });
        bg.add(codTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 80, 30));
        bg.add(codSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 80, 10));

        largoLbl.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        largoLbl.setForeground(new java.awt.Color(0, 0, 0));
        largoLbl.setText("LARGO");
        bg.add(largoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 60, 30));

        largoTxt.setBackground(new java.awt.Color(242, 242, 242));
        largoTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        largoTxt.setForeground(new java.awt.Color(0, 0, 0));
        largoTxt.setBorder(null);
        largoTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                largoTxtMousePressed(evt);
            }
        });
        largoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largoTxtActionPerformed(evt);
            }
        });
        largoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                largoTxtKeyPressed(evt);
            }
        });
        bg.add(largoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 80, 30));
        bg.add(largoSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 80, 10));

        anchoLbl.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        anchoLbl.setForeground(new java.awt.Color(0, 0, 0));
        anchoLbl.setText("ANCHO");
        bg.add(anchoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 60, 30));

        anchoTxt.setBackground(new java.awt.Color(242, 242, 242));
        anchoTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        anchoTxt.setForeground(new java.awt.Color(0, 0, 0));
        anchoTxt.setBorder(null);
        anchoTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                anchoTxtMousePressed(evt);
            }
        });
        anchoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anchoTxtActionPerformed(evt);
            }
        });
        anchoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                anchoTxtKeyPressed(evt);
            }
        });
        bg.add(anchoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 80, 30));
        bg.add(anchoSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 80, 10));

        espesorLbl.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        espesorLbl.setForeground(new java.awt.Color(0, 0, 0));
        espesorLbl.setText("ESPESOR");
        bg.add(espesorLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 60, 30));

        espesorTxt.setBackground(new java.awt.Color(242, 242, 242));
        espesorTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        espesorTxt.setForeground(new java.awt.Color(0, 0, 0));
        espesorTxt.setBorder(null);
        espesorTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                espesorTxtMousePressed(evt);
            }
        });
        espesorTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espesorTxtActionPerformed(evt);
            }
        });
        espesorTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                espesorTxtKeyPressed(evt);
            }
        });
        bg.add(espesorTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 80, 30));
        bg.add(espesorSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 80, 10));

        nuevoBtn.setBackground(new java.awt.Color(0, 96, 170));
        nuevoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        nuevoTxt.setBackground(new java.awt.Color(0, 96, 170));
        nuevoTxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        nuevoTxt.setForeground(new java.awt.Color(244, 247, 254));
        nuevoTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nuevoTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nueva-pagina.png"))); // NOI18N
        nuevoTxt.setText("NUEVO");
        nuevoTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nuevoTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nuevoTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nuevoTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nuevoTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout nuevoBtnLayout = new javax.swing.GroupLayout(nuevoBtn);
        nuevoBtn.setLayout(nuevoBtnLayout);
        nuevoBtnLayout.setHorizontalGroup(
            nuevoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nuevoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, Short.MAX_VALUE)
        );
        nuevoBtnLayout.setVerticalGroup(
            nuevoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nuevoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 17, Short.MAX_VALUE)
        );

        bg.add(nuevoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 110, 40));

        grabarBtn.setBackground(new java.awt.Color(0, 96, 170));
        grabarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        grabarTxt.setBackground(new java.awt.Color(0, 96, 170));
        grabarTxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        grabarTxt.setForeground(new java.awt.Color(244, 247, 254));
        grabarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grabarTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        grabarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        grabarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grabarTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                grabarTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                grabarTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout grabarBtnLayout = new javax.swing.GroupLayout(grabarBtn);
        grabarBtn.setLayout(grabarBtnLayout);
        grabarBtnLayout.setHorizontalGroup(
            grabarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grabarBtnLayout.createSequentialGroup()
                .addComponent(grabarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        grabarBtnLayout.setVerticalGroup(
            grabarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(grabarTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg.add(grabarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 60, 40));

        editarBtn.setBackground(new java.awt.Color(0, 96, 170));
        editarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        editarTxt.setBackground(new java.awt.Color(0, 96, 170));
        editarTxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        editarTxt.setForeground(new java.awt.Color(244, 247, 254));
        editarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editarTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        editarTxt.setText("EDITAR");
        editarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editarTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editarTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout editarBtnLayout = new javax.swing.GroupLayout(editarBtn);
        editarBtn.setLayout(editarBtnLayout);
        editarBtnLayout.setHorizontalGroup(
            editarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, Short.MAX_VALUE)
        );
        editarBtnLayout.setVerticalGroup(
            editarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 17, Short.MAX_VALUE)
        );

        bg.add(editarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 110, 40));

        borrarBtn.setBackground(new java.awt.Color(0, 96, 170));
        borrarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        borrarTxt.setBackground(new java.awt.Color(0, 96, 170));
        borrarTxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        borrarTxt.setForeground(new java.awt.Color(244, 247, 254));
        borrarTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        borrarTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/borrar.png"))); // NOI18N
        borrarTxt.setText("BORRAR");
        borrarTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        borrarTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrarTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                borrarTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                borrarTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout borrarBtnLayout = new javax.swing.GroupLayout(borrarBtn);
        borrarBtn.setLayout(borrarBtnLayout);
        borrarBtnLayout.setHorizontalGroup(
            borrarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(borrarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, Short.MAX_VALUE)
        );
        borrarBtnLayout.setVerticalGroup(
            borrarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(borrarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 17, Short.MAX_VALUE)
        );

        bg.add(borrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 110, 40));

        salirBtn.setBackground(new java.awt.Color(0, 96, 170));
        salirBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        salirTxt.setBackground(new java.awt.Color(0, 96, 170));
        salirTxt.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        salirTxt.setForeground(new java.awt.Color(244, 247, 254));
        salirTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salirTxt.setText("SALIR");
        salirTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salirTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout salirBtnLayout = new javax.swing.GroupLayout(salirBtn);
        salirBtn.setLayout(salirBtnLayout);
        salirBtnLayout.setHorizontalGroup(
            salirBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salirTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        salirBtnLayout.setVerticalGroup(
            salirBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salirTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg.add(salirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 110, 40));

        jScrollPane1.setBackground(new java.awt.Color(242, 242, 242));

        tblTipoMadera.setBackground(new java.awt.Color(242, 242, 242));
        tblTipoMadera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Espesor", "Ancho", "Largo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTipoMadera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTipoMaderaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTipoMadera);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 920, 310));

        bg_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo bl.jpg"))); // NOI18N
        bg.add(bg_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1020, 660));

        idTxt.setBackground(new java.awt.Color(242, 242, 242));
        idTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        idTxt.setForeground(new java.awt.Color(204, 204, 204));
        idTxt.setBorder(null);
        idTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                idTxtMousePressed(evt);
            }
        });
        idTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTxtActionPerformed(evt);
            }
        });
        idTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idTxtKeyPressed(evt);
            }
        });
        bg.add(idTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codTxtActionPerformed

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        dispose();
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(new Color(244, 247, 254));
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitBtn.setBackground(new Color(244, 247, 254));
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

    private void nuevoTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoTxtMouseEntered
        if (nuevoTxt.isEnabled()) {
            nuevoBtn.setBackground(new Color(0, 156, 223));
        }
    }//GEN-LAST:event_nuevoTxtMouseEntered

    private void nuevoTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoTxtMouseExited
        if (nuevoTxt.isEnabled()) {
            nuevoBtn.setBackground(new Color(0, 96, 170));
        }
    }//GEN-LAST:event_nuevoTxtMouseExited

    private void codTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codTxtMousePressed

    }//GEN-LAST:event_codTxtMousePressed

    private void nuevoTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoTxtMouseClicked
        limpiar();
        habilitarBotones(true, true, true, true, false, true, false, false, true);
    }//GEN-LAST:event_nuevoTxtMouseClicked

    private void codTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codTxtKeyPressed

    }//GEN-LAST:event_codTxtKeyPressed

    private void espesorTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espesorTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_espesorTxtMousePressed

    private void espesorTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espesorTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_espesorTxtActionPerformed

    private void espesorTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_espesorTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_espesorTxtKeyPressed

    private void anchoTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anchoTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_anchoTxtMousePressed

    private void anchoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anchoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anchoTxtActionPerformed

    private void anchoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anchoTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_anchoTxtKeyPressed

    private void largoTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_largoTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_largoTxtMousePressed

    private void largoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_largoTxtActionPerformed

    private void largoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_largoTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_largoTxtKeyPressed

    private void salirTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirTxtMouseClicked
        dispose();
    }//GEN-LAST:event_salirTxtMouseClicked

    private void salirTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirTxtMouseEntered
        if (salirTxt.isEnabled()) {
            salirBtn.setBackground(new Color(0, 156, 223));
        }
    }//GEN-LAST:event_salirTxtMouseEntered

    private void salirTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirTxtMouseExited
        if (salirTxt.isEnabled()) {
            salirBtn.setBackground(new Color(0, 96, 170));
        }
    }//GEN-LAST:event_salirTxtMouseExited

    private void borrarTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarTxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_borrarTxtMouseClicked

    private void borrarTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarTxtMouseEntered
        if (borrarTxt.isEnabled()) {
            borrarBtn.setBackground(new Color(0, 156, 223));
        }
    }//GEN-LAST:event_borrarTxtMouseEntered

    private void borrarTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarTxtMouseExited
        if (borrarTxt.isEnabled()) {
            borrarBtn.setBackground(new Color(0, 96, 170));
        }
    }//GEN-LAST:event_borrarTxtMouseExited

    private void grabarTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grabarTxtMouseClicked
        String nombreMadera;
        double largo, ancho, espesor;

        nombreMadera = codTxt.getText();
        largo = Double.parseDouble(largoTxt.getText());
        ancho = Double.parseDouble(anchoTxt.getText());
        espesor = Double.parseDouble(espesorTxt.getText());

        DTOTipoMadera oProd = new DTOTipoMadera();
        oProd.setNombreMadera(nombreMadera);
        oProd.setLargo(largo);
        oProd.setAncho(ancho);
        oProd.setEspesor(espesor);

        DAOTipoMadera oDProd = new DAOTipoMadera();
        oDProd.agregarMadera(oProd);

        verProducto();
        limpiar();
        habilitarBotones(false, false, false, false, true, false, false, false, true);
    }//GEN-LAST:event_grabarTxtMouseClicked

    private void grabarTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grabarTxtMouseEntered
        if (grabarTxt.isEnabled()) {
            grabarBtn.setBackground(new Color(0, 156, 223));
        }
    }//GEN-LAST:event_grabarTxtMouseEntered

    private void grabarTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grabarTxtMouseExited
        if (grabarTxt.isEnabled()) {
            grabarBtn.setBackground(new Color(0, 96, 170));
        }
    }//GEN-LAST:event_grabarTxtMouseExited

    private void editarTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarTxtMouseClicked
        int idMadera;
        String nombreMadera;
        double largo, ancho, espesor;

        idMadera = Integer.parseInt(idTxt.getText());
        nombreMadera = codTxt.getText();
        largo = Double.parseDouble(largoTxt.getText());
        ancho = Double.parseDouble(anchoTxt.getText());
        espesor = Double.parseDouble(espesorTxt.getText());

        DTOTipoMadera oMad = new DTOTipoMadera();
        oMad.setIdMadera(idMadera);
        oMad.setNombreMadera(nombreMadera);
        oMad.setLargo(largo);
        oMad.setAncho(ancho);
        oMad.setEspesor(espesor);

        DAOTipoMadera oDMad = new DAOTipoMadera();
        oDMad.editarMadera(oMad);

        verProducto();
        limpiar();
        
    }//GEN-LAST:event_editarTxtMouseClicked

    private void editarTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarTxtMouseEntered
        if (editarTxt.isEnabled()) {
            editarBtn.setBackground(new Color(0, 156, 223));
        }
    }//GEN-LAST:event_editarTxtMouseEntered

    private void editarTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarTxtMouseExited
        if (editarTxt.isEnabled()) {
            editarBtn.setBackground(new Color(0, 96, 170));
        }
    }//GEN-LAST:event_editarTxtMouseExited

    private void tblTipoMaderaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTipoMaderaMouseClicked
        int fila;
        fila = tblTipoMadera.getSelectedRow();
        String id, nombre, largo, ancho, espesor;
        id = (String) tblTipoMadera.getValueAt(fila, 0);
        nombre = (String) tblTipoMadera.getValueAt(fila, 1);
        largo = (String) tblTipoMadera.getValueAt(fila, 2);
        ancho = (String) tblTipoMadera.getValueAt(fila, 3);
        espesor = (String) tblTipoMadera.getValueAt(fila, 4);

        idTxt.setText(id);
        codTxt.setText(nombre);
        largoTxt.setText(largo);
        anchoTxt.setText(ancho);
        espesorTxt.setText(espesor);
        habilitarBotones(true, true, true, true, false, false, true, true, true);
    }//GEN-LAST:event_tblTipoMaderaMouseClicked

    private void idTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idTxtMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTxtMousePressed

    private void idTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTxtActionPerformed

    private void idTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTxtKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTpMadera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTpMadera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTpMadera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTpMadera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTpMadera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anchoLbl;
    private javax.swing.JSeparator anchoSeparator;
    private javax.swing.JTextField anchoTxt;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel bg_img;
    private javax.swing.JPanel borrarBtn;
    private javax.swing.JLabel borrarTxt;
    private javax.swing.JLabel codLbl;
    private javax.swing.JSeparator codSeparator;
    private javax.swing.JTextField codTxt;
    private javax.swing.JPanel editarBtn;
    private javax.swing.JLabel editarTxt;
    private javax.swing.JLabel espesorLbl;
    private javax.swing.JSeparator espesorSeparator;
    private javax.swing.JTextField espesorTxt;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JLabel fotoMadera;
    private javax.swing.JPanel grabarBtn;
    private javax.swing.JLabel grabarTxt;
    private javax.swing.JPanel header;
    private javax.swing.JTextField idTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel largoLbl;
    private javax.swing.JSeparator largoSeparator;
    private javax.swing.JTextField largoTxt;
    private javax.swing.JPanel nuevoBtn;
    private javax.swing.JLabel nuevoTxt;
    private javax.swing.JPanel salirBtn;
    private javax.swing.JLabel salirTxt;
    private javax.swing.JTable tblTipoMadera;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
